### ISSUE TITLE
How do you set the whole thing up ?

### ISSUE THREAD

**Issue by abrhambas01** [NikolayOskin/laravel-vuejs-socketio-chat#2]
Sir, how do u set it up ? ??
```
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
(node:14488) UnhandledPromiseRejectionWarning: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (F:\laragon_2\www\laravel-vuejs-socketio-chat\node_modules\ioredis\built\redis\event_handler.js:108:37)
    at Object.onceWrapper (events.js:288:20)
    at Socket.emit (events.js:200:13)
    at TCP.<anonymous> (net.js:588:12)
(node:14488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by ngdevc** [comment]
i have faced same error. Have you solved this successfully?
